trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false


  displayName1: 'Compile Sass assets'

  displayName2: 'Run gulp tasks'


  displayName3: 'Write build info'



  displayName4: 'Restore project dependencies'



  displayName5: 'Build the project 



  displayName5: 'Run unit tests
  inputs:
    command: 'test'
    



  displayName6: 'Publish the project 
  inputs:
    command: 'publish'



  displayName7: 'Publish Artifact: drop'
  condition: succeeded()
